[2025-03-10T16:47:36.815+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-10T16:47:36.835+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: xkcd_daily.dbt_test manual__2025-03-10T16:47:24.863746+00:00 [queued]>
[2025-03-10T16:47:36.842+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: xkcd_daily.dbt_test manual__2025-03-10T16:47:24.863746+00:00 [queued]>
[2025-03-10T16:47:36.843+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-10T16:47:36.859+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): dbt_test> on 2025-03-10 16:47:24.863746+00:00
[2025-03-10T16:47:36.863+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=3357) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-10T16:47:36.864+0000] {standard_task_runner.py:72} INFO - Started process 3358 to run task
[2025-03-10T16:47:36.864+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'xkcd_daily', 'dbt_test', 'manual__2025-03-10T16:47:24.863746+00:00', '--job-id', '166', '--raw', '--subdir', 'DAGS_FOLDER/XKCD_daily/dag.py', '--cfg-path', '/tmp/tmpmc9fzbys']
[2025-03-10T16:47:36.865+0000] {standard_task_runner.py:105} INFO - Job 166: Subtask dbt_test
[2025-03-10T16:47:36.882+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-10T16:47:36.921+0000] {task_command.py:467} INFO - Running <TaskInstance: xkcd_daily.dbt_test manual__2025-03-10T16:47:24.863746+00:00 [running]> on host 157a64d0872f
[2025-03-10T16:47:37.000+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='xkcd_daily' AIRFLOW_CTX_TASK_ID='dbt_test' AIRFLOW_CTX_EXECUTION_DATE='2025-03-10T16:47:24.863746+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-10T16:47:24.863746+00:00'
[2025-03-10T16:47:37.000+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-10T16:47:37.008+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-10T16:47:37.009+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /dbt/transformations && dbt test --project-dir /dbt/transformations --profiles-dir /dbt']
[2025-03-10T16:47:37.015+0000] {subprocess.py:99} INFO - Output:
[2025-03-10T16:47:38.576+0000] {subprocess.py:106} INFO - [0m16:47:38  Running with dbt=1.9.3
[2025-03-10T16:47:38.802+0000] {subprocess.py:106} INFO - [0m16:47:38  Registered adapter: postgres=1.9.0
[2025-03-10T16:47:39.036+0000] {subprocess.py:106} INFO - [0m16:47:39  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2025-03-10T16:47:39.037+0000] {subprocess.py:106} INFO - There are 1 unused configuration paths:
[2025-03-10T16:47:39.037+0000] {subprocess.py:106} INFO - - models.transformations.example
[2025-03-10T16:47:39.178+0000] {subprocess.py:106} INFO - [0m16:47:39  Found 5 models, 2 data tests, 1 source, 433 macros
[2025-03-10T16:47:39.180+0000] {subprocess.py:106} INFO - [0m16:47:39
[2025-03-10T16:47:39.181+0000] {subprocess.py:106} INFO - [0m16:47:39  Concurrency: 1 threads (target='prod')
[2025-03-10T16:47:39.181+0000] {subprocess.py:106} INFO - [0m16:47:39
[2025-03-10T16:47:39.278+0000] {subprocess.py:106} INFO - [0m16:47:39  1 of 2 START test not_null_dim_comics_num ...................................... [RUN]
[2025-03-10T16:47:39.335+0000] {subprocess.py:106} INFO - [0m16:47:39  1 of 2 PASS not_null_dim_comics_num ............................................ [[32mPASS[0m in 0.06s]
[2025-03-10T16:47:39.337+0000] {subprocess.py:106} INFO - [0m16:47:39  2 of 2 START test unique_dim_comics_num ........................................ [RUN]
[2025-03-10T16:47:39.386+0000] {subprocess.py:106} INFO - [0m16:47:39  2 of 2 PASS unique_dim_comics_num .............................................. [[32mPASS[0m in 0.05s]
[2025-03-10T16:47:39.404+0000] {subprocess.py:106} INFO - [0m16:47:39
[2025-03-10T16:47:39.405+0000] {subprocess.py:106} INFO - [0m16:47:39  Finished running 2 data tests in 0 hours 0 minutes and 0.22 seconds (0.22s).
[2025-03-10T16:47:39.447+0000] {subprocess.py:106} INFO - [0m16:47:39
[2025-03-10T16:47:39.447+0000] {subprocess.py:106} INFO - [0m16:47:39  [32mCompleted successfully[0m
[2025-03-10T16:47:39.447+0000] {subprocess.py:106} INFO - [0m16:47:39
[2025-03-10T16:47:39.448+0000] {subprocess.py:106} INFO - [0m16:47:39  Done. PASS=2 WARN=0 ERROR=0 SKIP=0 TOTAL=2
[2025-03-10T16:47:40.067+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-03-10T16:47:40.109+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-10T16:47:40.109+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=xkcd_daily, task_id=dbt_test, run_id=manual__2025-03-10T16:47:24.863746+00:00, execution_date=20250310T164724, start_date=20250310T164736, end_date=20250310T164740
[2025-03-10T16:47:40.166+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-10T16:47:40.191+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-10T16:47:40.208+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
