[2025-03-10T14:27:25.610+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-10T14:27:25.630+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: xkcd_daily.dbt_run manual__2025-03-10T14:20:39.848994+00:00 [queued]>
[2025-03-10T14:27:25.635+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: xkcd_daily.dbt_run manual__2025-03-10T14:20:39.848994+00:00 [queued]>
[2025-03-10T14:27:25.636+0000] {taskinstance.py:2867} INFO - Starting attempt 5 of 6
[2025-03-10T14:27:25.648+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): dbt_run> on 2025-03-10 14:20:39.848994+00:00
[2025-03-10T14:27:25.652+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=233) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-10T14:27:25.653+0000] {standard_task_runner.py:72} INFO - Started process 234 to run task
[2025-03-10T14:27:25.652+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'xkcd_daily', 'dbt_run', 'manual__2025-03-10T14:20:39.848994+00:00', '--job-id', '152', '--raw', '--subdir', 'DAGS_FOLDER/XKCD_daily/dag.py', '--cfg-path', '/tmp/tmpztfcij6o']
[2025-03-10T14:27:25.654+0000] {standard_task_runner.py:105} INFO - Job 152: Subtask dbt_run
[2025-03-10T14:27:25.670+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-10T14:27:25.726+0000] {task_command.py:467} INFO - Running <TaskInstance: xkcd_daily.dbt_run manual__2025-03-10T14:20:39.848994+00:00 [running]> on host 157a64d0872f
[2025-03-10T14:27:25.807+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='xkcd_daily' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2025-03-10T14:20:39.848994+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-10T14:20:39.848994+00:00'
[2025-03-10T14:27:25.808+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-10T14:27:25.819+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-10T14:27:25.819+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /dbt/transformations && dbt run --project-dir /dbt/transformations --profiles-dir /dbt']
[2025-03-10T14:27:25.824+0000] {subprocess.py:99} INFO - Output:
[2025-03-10T14:27:27.036+0000] {subprocess.py:106} INFO - [0m14:27:27  Running with dbt=1.9.3
[2025-03-10T14:27:27.191+0000] {subprocess.py:106} INFO - [0m14:27:27  Registered adapter: postgres=1.9.0
[2025-03-10T14:27:27.621+0000] {subprocess.py:106} INFO - [0m14:27:27  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2025-03-10T14:27:27.621+0000] {subprocess.py:106} INFO - There are 1 unused configuration paths:
[2025-03-10T14:27:27.622+0000] {subprocess.py:106} INFO - - models.transformations.example
[2025-03-10T14:27:27.726+0000] {subprocess.py:106} INFO - [0m14:27:27  Found 2 models, 1 source, 433 macros
[2025-03-10T14:27:27.728+0000] {subprocess.py:106} INFO - [0m14:27:27
[2025-03-10T14:27:27.728+0000] {subprocess.py:106} INFO - [0m14:27:27  Concurrency: 1 threads (target='prod')
[2025-03-10T14:27:27.729+0000] {subprocess.py:106} INFO - [0m14:27:27
[2025-03-10T14:27:27.936+0000] {subprocess.py:106} INFO - [0m14:27:27  1 of 2 START sql table model dbt_dwh.dim_comics ................................ [RUN]
[2025-03-10T14:27:28.102+0000] {subprocess.py:106} INFO - [0m14:27:28  1 of 2 OK created sql table model dbt_dwh.dim_comics ........................... [[32mSELECT 561[0m in 0.16s]
[2025-03-10T14:27:28.104+0000] {subprocess.py:106} INFO - [0m14:27:28  2 of 2 START sql table model dbt_dwh.fact_review ............................... [RUN]
[2025-03-10T14:27:28.187+0000] {subprocess.py:106} INFO - [0m14:27:28  2 of 2 OK created sql table model dbt_dwh.fact_review .......................... [[32mSELECT 561[0m in 0.08s]
[2025-03-10T14:27:28.207+0000] {subprocess.py:106} INFO - [0m14:27:28
[2025-03-10T14:27:28.208+0000] {subprocess.py:106} INFO - [0m14:27:28  Finished running 2 table models in 0 hours 0 minutes and 0.48 seconds (0.48s).
[2025-03-10T14:27:28.252+0000] {subprocess.py:106} INFO - [0m14:27:28
[2025-03-10T14:27:28.256+0000] {subprocess.py:106} INFO - [0m14:27:28  [32mCompleted successfully[0m
[2025-03-10T14:27:28.259+0000] {subprocess.py:106} INFO - [0m14:27:28
[2025-03-10T14:27:28.259+0000] {subprocess.py:106} INFO - [0m14:27:28  Done. PASS=2 WARN=0 ERROR=0 SKIP=0 TOTAL=2
[2025-03-10T14:27:28.818+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-03-10T14:27:28.872+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-10T14:27:28.873+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=xkcd_daily, task_id=dbt_run, run_id=manual__2025-03-10T14:20:39.848994+00:00, execution_date=20250310T142039, start_date=20250310T142725, end_date=20250310T142728
[2025-03-10T14:27:28.956+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-10T14:27:28.976+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-10T14:27:28.979+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
